# This is a basic workflow to help you get started with Actions

name: ghp-deploy

permissions:
  contents: write
  repository-projects: write
  pages: write
  id-token: write

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:  
      - uses: actions/checkout@v3

      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
          
      - name: Publish app
        run: dotnet publish ThreeTacos.Tacomponents.Demo/ThreeTacos.Tacomponents.Demo.csproj -c Release

      - name: Rewrite base href
        uses: SteveSandersonMS/ghaction-rewrite-base-href@v1
        with:
          html_path: ThreeTacos.Tacomponents.Demo/bin/Release/net6.0/publish/wwwroot/index.html
          base_href: /tacomponents/

      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: ThreeTacos.Tacomponents.Demo/bin/Release/net6.0/publish/wwwroot/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
